const mongoose = require('mongoose');
const Saint = require('../models/Saint');
require('dotenv').config();

const saints = [
  { tag: 'પૂ.', name: 'Gyanjivandasji Swami' },
  { tag: 'પૂ.', name: 'Narayanmunidasji Swami' },
  { tag: 'પૂ.', name: 'Dharmaswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Nirmaldasji Swami' },
  { tag: 'પૂ.', name: 'Shyamcharandasji Swami' },
  { tag: 'પૂ.', name: 'Ishwarcharandasji Swami' },
  { tag: 'પૂ.', name: 'Nandkishordasji Swami' },
  { tag: 'પૂ.', name: 'Ghanshyamjivandasji Swami' },
  { tag: 'પૂ.', name: 'Aksharjivandasji Swami' },
  { tag: 'પૂ.', name: 'Achyutdasji Swami' },
  { tag: 'પૂ.', name: 'Sarjudasji Swami' },
  { tag: 'પૂ.', name: 'Madhavpriyadasji Swami' },
  { tag: 'પૂ.', name: 'Niranjandasji Swami' },
  { tag: 'પૂ.', name: 'Vivekswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Krushnapriyadasji Swami' },
  { tag: 'પૂ.', name: 'Shreerangdasji Swami' },
  { tag: 'પૂ.', name: 'Pavitrajivandasji Swami' },
  { tag: 'પૂ.', name: 'Tyagvallabhdasji Swami' },
  { tag: 'પૂ.', name: 'Sadhujivandasji Swami' },
  { tag: 'પૂ.', name: 'Akhiljivandasji Swami' },
  { tag: 'પૂ.', name: 'Bhajanprakashdasji Swami' },
  { tag: 'પૂ.', name: 'Sanatandasji Swami' },
  { tag: 'પૂ.', name: 'Santdasji Swami' },
  { tag: 'પૂ.', name: 'Nyalkarandasji Swami' },
  { tag: 'પૂ.', name: 'Videhswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Mangalswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Achalswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Puratandasji Swami' },
  { tag: 'પૂ.', name: 'Ramdasji Swami' },
  { tag: 'પૂ.', name: 'Uttamcharandasji Swami' },
  { tag: 'પૂ.', name: 'Shreejiswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Sakarswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Anandswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Sadruchidasji Swami' },
  { tag: 'પૂ.', name: 'Anuvruttidasji Swami' },
  { tag: 'પૂ.', name: 'Varniveshdasji Swami' },
  { tag: 'પૂ.', name: 'Anadiswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Karanswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Adarshjivandasji Swami' },
  { tag: 'પૂ.', name: 'Sadgundasji Swami' },
  { tag: 'પૂ.', name: 'Prasannavadandasji Swami' },
  { tag: 'પૂ.', name: 'Chinmayswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Pratyakshswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Parswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Sankirtandasji Swami' },
  { tag: 'પૂ.', name: 'Anvayswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Hradayprakashdasji Swami' },
  { tag: 'પૂ.', name: 'Aishvaryaprakashdasji Swami' },
  { tag: 'પૂ.', name: 'Harigundasji Swami' },
  { tag: 'પૂ.', name: 'Atmiyaswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Murtiswarupdasji Swami' },
  { tag: 'પૂ.', name: 'Sahanpriyadasji Swami' },
  { tag: 'પા.', name: 'Chatur Bhagat' },
  { tag: 'પા.', name: 'Girish Bhagat' },
  { tag: 'પા.', name: 'Jayanti Bhagat' },
  { tag: 'પા.', name: 'Dharam Bhagat' },
  { tag: 'પા.', name: 'Vinay Bhagat' },
  { tag: 'પા.', name: 'Praful Bhagat' },
  { tag: 'પા.', name: 'Ghanshyam Bhagat' },
  { tag: 'પા.', name: 'Dhanji Bhagat' },
  { tag: 'પા.', name: 'Radhesh Bhagat' },
  { tag: 'સા.', name: 'Paresh Bhagat' },
  { tag: 'સા.', name: 'Mayank Bhagat' },
  { tag: 'સા.', name: 'Hiren Bhagat' },
  { tag: 'સા.', name: 'Mitul Bhagat' },
  { tag: 'સા.', name: 'Keyur Bhagat' },
  { tag: 'સા.', name: 'Raghu Bhagat' },
  { tag: 'સા.', name: 'Vipul Bhagat' },
  { tag: 'સા.', name: 'Maharshi Bhagat' },
  { tag: 'સા.', name: 'Bharat Bhagat' },
  { tag: 'સા.', name: 'Chintan Bhagat' },
  { tag: 'સા.', name: 'Tilak Bhagat' },
  { tag: 'સા.', name: 'Mahesh Bhagat' },
  { tag: 'સા.', name: 'Santosh Bhagat' },
  { tag: 'મુ.', name: 'Chirag Bhagat' },
  { tag: 'મુ.', name: 'Chetan Bhagat' },
  { tag: 'મુ.', name: 'Rignesh Bhagat' },
  { tag: 'મુ.', name: 'Vimal Bhagat' },
  { tag: 'સે.', name: 'Amit Bhagat' },
  { tag: 'સે.', name: 'Ghanshyam Bhagat' },
  { tag: 'સે.', name: 'Narendra Bhagat' },
  { tag: 'સે.', name: 'Sumit Bhagat' },
  { tag: 'સે.', name: 'Mayur Bhagat' },
  { tag: 'સે.', name: 'Alpesh Bhagat' },
  { tag: 'સે.', name: 'Vishal Bhagat' },
  { tag: 'સે.', name: 'Dhaval Bhagat' }
];

async function insertSaints() {
  await mongoose.connect(process.env.MONGODB_URI);
  await Saint.deleteMany({});
  await Saint.insertMany(saints);
  console.log('Saints inserted successfully');
  mongoose.disconnect();
}

insertSaints();
